spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtest?characterEncoding=utf8&useSSL=false&autoReconnect=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090
  servlet:
    context-path: /api